name: release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: main
      - name: Clone Global Repo
        uses: actions/checkout@v3
        with:
          repository: Tackem-org/Global
          path: Global
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '>=1.18'
          working-directory: ./main
      -
        name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      # -
      #   name: Tests
      #   run: |
      #     go mod tidy
      #     go test -v ./...
      #   with:
      #     working-directory: ./main
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
          workdir: ./main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
